#!/bin/sh
# ───── enmarket API entrypoint ─────
# 1. Tunggu DB siap
# 2. Inject container env vars ke .env (PHP dev server workers tidak inherit env)
# 3. Generate APP_KEY kalau belum ada
# 4. Jalankan migrate
# 5. Start CMD

set -e

cd /var/www/html

echo "⏳ Waiting for database..."
ATTEMPTS=0
MAX=30
until php -r "try { new PDO('mysql:host=' . getenv('DB_HOST') . ';port=' . getenv('DB_PORT') . ';dbname=' . getenv('DB_DATABASE'), getenv('DB_USERNAME'), getenv('DB_PASSWORD')); echo \"DB OK\\n\"; exit(0); } catch (Throwable \$e) { exit(1); }" 2>/dev/null; do
    ATTEMPTS=$((ATTEMPTS+1))
    if [ "$ATTEMPTS" -ge "$MAX" ]; then
        echo "❌ Database tidak siap setelah ${MAX} attempts"
        exit 1
    fi
    echo "   waiting... ($ATTEMPTS/$MAX)"
    sleep 2
done

# ───── Inject runtime env ke .env ─────
# PHP -S (dipakai artisan serve) tidak inherit env ke workers, jadi kita
# tulis ulang .env dengan nilai container yang aktif agar Laravel Dotenv
# membaca nilai benar apapun cara PHP dipanggil.
echo "🔧 Injecting container env into .env..."

KEY_BLOCK="# Auto-generated by entrypoint — do not edit manually"

# Generate APP_KEY kalau belum di-set
if [ -z "${APP_KEY:-}" ]; then
    GENERATED_KEY=$(php artisan key:generate --show --no-interaction 2>/dev/null | tail -1)
    echo "🔑 Generated APP_KEY"
else
    GENERATED_KEY="$APP_KEY"
fi

cat > /var/www/html/.env <<EOF
$KEY_BLOCK
APP_NAME="${APP_NAME:-enmarket API}"
APP_ENV=${APP_ENV:-local}
APP_KEY=${GENERATED_KEY}
APP_DEBUG=${APP_DEBUG:-true}
APP_URL=${APP_URL:-http://localhost:8000}

LOG_CHANNEL=${LOG_CHANNEL:-stack}

DB_CONNECTION=${DB_CONNECTION:-mysql}
DB_HOST=${DB_HOST:-127.0.0.1}
DB_PORT=${DB_PORT:-3306}
DB_DATABASE=${DB_DATABASE:-enmarket}
DB_USERNAME=${DB_USERNAME:-enmarket}
DB_PASSWORD=${DB_PASSWORD:-secret}

SESSION_DRIVER=${SESSION_DRIVER:-database}
SESSION_LIFETIME=120

BROADCAST_CONNECTION=log
FILESYSTEM_DISK=local
QUEUE_CONNECTION=${QUEUE_CONNECTION:-database}

CACHE_STORE=${CACHE_STORE:-database}

MAIL_MAILER=${MAIL_MAILER:-log}
MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-noreply@enpiistudio.com}
MAIL_FROM_NAME="\${APP_NAME}"

# Tripay (Fase 3)
TRIPAY_MODE=${TRIPAY_MODE:-sandbox}
TRIPAY_API_KEY=${TRIPAY_API_KEY:-}
TRIPAY_PRIVATE_KEY=${TRIPAY_PRIVATE_KEY:-}
TRIPAY_MERCHANT_CODE=${TRIPAY_MERCHANT_CODE:-}
TRIPAY_CALLBACK_URL=${TRIPAY_CALLBACK_URL:-}

# EnStorage (Fase 4)
ENSTORAGE_MOCK=${ENSTORAGE_MOCK:-true}
ENSTORAGE_BASE_URL=${ENSTORAGE_BASE_URL:-}
ENSTORAGE_API_KEY=${ENSTORAGE_API_KEY:-}

# Evolution API (Fase 4)
EVOLUTION_API_URL=${EVOLUTION_API_URL:-}
EVOLUTION_API_KEY=${EVOLUTION_API_KEY:-}
EVOLUTION_INSTANCE=${EVOLUTION_INSTANCE:-enpiistudio}

# n8n (Fase 4)
N8N_WEBHOOK_KIRIM_PRODUK=${N8N_WEBHOOK_KIRIM_PRODUK:-}

# SMTP (Fase 4)
MAIL_HOST=${MAIL_HOST:-}
MAIL_PORT=${MAIL_PORT:-}
MAIL_USERNAME=${MAIL_USERNAME:-}
MAIL_PASSWORD=${MAIL_PASSWORD:-}

# Admin (Fase 1)
ADMIN_TOKEN=${ADMIN_TOKEN:-dev-admin-token-12345}
CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:3000,http://127.0.0.1:3000}
EOF

# Cache clear
php artisan config:clear 2>/dev/null || true
php artisan route:clear 2>/dev/null || true
php artisan cache:clear 2>/dev/null || true

# Storage symlink
php artisan storage:link 2>/dev/null || true

# Run migrations
php artisan migrate --force --no-interaction

echo "✅ API ready, starting server..."
exec "$@"